// ReSharper disable InconsistentNaming

namespace Midi.Win32
{
    /// <summary>
    ///     Status type returned from most functions in the Win32 API.
    /// </summary>
    internal enum MMRESULT : uint
    {
        // General return codes.
        MMSYSERR_BASE = 0,
        MMSYSERR_NOERROR = MMSYSERR_BASE + 0,
        MMSYSERR_ERROR = MMSYSERR_BASE + 1,
        MMSYSERR_BADDEVICEID = MMSYSERR_BASE + 2,
        MMSYSERR_NOTENABLED = MMSYSERR_BASE + 3,
        MMSYSERR_ALLOCATED = MMSYSERR_BASE + 4,
        MMSYSERR_INVALHANDLE = MMSYSERR_BASE + 5,
        MMSYSERR_NODRIVER = MMSYSERR_BASE + 6,
        MMSYSERR_NOMEM = MMSYSERR_BASE + 7,
        MMSYSERR_NOTSUPPORTED = MMSYSERR_BASE + 8,
        MMSYSERR_BADERRNUM = MMSYSERR_BASE + 9,
        MMSYSERR_INVALFLAG = MMSYSERR_BASE + 10,
        MMSYSERR_INVALPARAM = MMSYSERR_BASE + 11,
        MMSYSERR_HANDLEBUSY = MMSYSERR_BASE + 12,
        MMSYSERR_INVALIDALIAS = MMSYSERR_BASE + 13,
        MMSYSERR_BADDB = MMSYSERR_BASE + 14,
        MMSYSERR_KEYNOTFOUND = MMSYSERR_BASE + 15,
        MMSYSERR_READERROR = MMSYSERR_BASE + 16,
        MMSYSERR_WRITEERROR = MMSYSERR_BASE + 17,
        MMSYSERR_DELETEERROR = MMSYSERR_BASE + 18,
        MMSYSERR_VALNOTFOUND = MMSYSERR_BASE + 19,
        MMSYSERR_NODRIVERCB = MMSYSERR_BASE + 20,
        MMSYSERR_MOREDATA = MMSYSERR_BASE + 21,
        MMSYSERR_LASTERROR = MMSYSERR_BASE + 21,

        // MIDI-specific return codes.
        MIDIERR_BASE = 64,
        MIDIERR_UNPREPARED = MIDIERR_BASE + 0,
        MIDIERR_STILLPLAYING = MIDIERR_BASE + 1,
        MIDIERR_NOMAP = MIDIERR_BASE + 2,
        MIDIERR_NOTREADY = MIDIERR_BASE + 3,
        MIDIERR_NODEVICE = MIDIERR_BASE + 4,
        MIDIERR_INVALIDSETUP = MIDIERR_BASE + 5,
        MIDIERR_BADOPENMODE = MIDIERR_BASE + 6,
        MIDIERR_DONT_CONTINUE = MIDIERR_BASE + 7,
        MIDIERR_LASTERROR = MIDIERR_BASE + 7
    }
}